// <auto-generated />
using MBExplorer.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace MBExplorer.Migrations
{
    [DbContext(typeof(BookmarkDbContext))]
    [Migration("20171206141155_mappedItemUrl")]
    partial class mappedItemUrl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MBExplorer.Core.Models.Bookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Bookmarks");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Bookmark");
                });

            modelBuilder.Entity("MBExplorer.Core.Models.Folder", b =>
                {
                    b.HasBaseType("MBExplorer.Core.Models.Bookmark");


                    b.ToTable("Folder");

                    b.HasDiscriminator().HasValue("Folder");
                });

            modelBuilder.Entity("MBExplorer.Core.Models.ItemLink", b =>
                {
                    b.HasBaseType("MBExplorer.Core.Models.Bookmark");

                    b.Property<string>("URL")
                        .HasMaxLength(3000);

                    b.ToTable("ItemLink");

                    b.HasDiscriminator().HasValue("ItemLink");
                });

            modelBuilder.Entity("MBExplorer.Core.Models.ItemLocation", b =>
                {
                    b.HasBaseType("MBExplorer.Core.Models.Bookmark");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.ToTable("ItemLocation");

                    b.HasDiscriminator().HasValue("ItemLocation");
                });

            modelBuilder.Entity("MBExplorer.Core.Models.ItemTextFile", b =>
                {
                    b.HasBaseType("MBExplorer.Core.Models.Bookmark");

                    b.Property<string>("FileContent");

                    b.Property<string>("FileName")
                        .HasMaxLength(250);

                    b.ToTable("ItemTextFile");

                    b.HasDiscriminator().HasValue("ItemTextFile");
                });
#pragma warning restore 612, 618
        }
    }
}
